version: '3.7'
services: 
  arangodb:
    container_name: orango
    image: arangodb:3.4.1
    ports: 
      - 8529:8529
    environment: 
      ARANGO_NO_AUTH: 1
    volumes:
      - ./docker/orango/db:/var/lib/arangodb3
      - ./docker/orango/apps:/var/lib/arangodb3-apps